export const LOAD_DATA = 'LOAD_DATA';
export const SELECT_SEASON = 'SELECT_SEASON';
export const GET_INFO_CHARACTER = 'GET_INFO_CHARACTER';
export const CLEAN_INFO_CHARACTER = 'CLEAN_INFO_CHARACTER';
